app_web:
    resource: "@AppBundle/Controller/Web"
    type:     annotation

app_api:
    resource: "@AppBundle/Controller/API"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"